drop table bookings if exists;
create table bookings (
    id bigint generated by default as identity,
    email varchar(255) not null,
    paid boolean default false,
    flight_id bigint not null,
    primary key (id)
);

drop table flights if exists;
create table flights (
    id bigint generated by default as identity,
    destination varchar(255) not null,
    primary key (id)
);

drop table audit_logs if exists;
create table audit_logs (
    id bigint generated by default as identity,
    created timestamp not null,
    description varchar(255) not null,
    primary key (id)
);

alter table bookings
    add constraint flight_fk 
    foreign key (flight_id) 
    references flights;

delete from flights;
insert into flights (id, destination) values (1, 'London');
insert into flights (id, destination) values (2, 'Oslo');
insert into flights (id, destination) values (3, 'Paris');